### ISSUE TITLE
How i create a sub domain for each user?

### ISSUE THREAD

**Issue by surendrakumar1992** [bmullan91/express-subdomain#26]
I am working on MEAN application. I want to create a unique subdomain for each user. If any one visit that unique sub domain then information will show accordingly.How i will handle this in local as well production? I don't want to use A record because i need this in dynamic way.

Thanks in advance

**Comment by rusintez** [comment]
what about dynamic A ? eg. `*.domain.com` points to `domain.com`?

then in your router

```javascript

// get your dynamic subdomain

app.use(function(req, res, next) {
  if (!req.subdomains.length || req.subdomains.slice(-1)[0] === 'www') return next();
  // otherwise we have subdomain here
  var subdomain = req.subdomains.slice(-1)[0];
  // keep it
  req.subdomain = subdomain;
  next();
});


// render a page
app.get('/', function(req, res) {
  // no subdomain
  if (!req.subdomain) {
  }
});

```

**Comment by surendrakumar1992** [comment]
@rusintez 
Thanks for quick response
I want like this 
My main domain is www.demo.com. Now if user surendra create a new account then he can access surendra.demo.com instantly. so i can dynmic handle subdomain. How i can setup it local also

Thanks in advance

**Comment by rusintez** [comment]
1. for local wildcard subdomain development check something like http://pow.cx/ - it works with node.js
2. the example above is exactly what you need in order to serve user-specific content based on subdomain.

**Comment by surendrakumar1992** [comment]
Thanks for your quick response.
I got your point and i know it will work now query is that how i point 'N' number of sub domain. Each new user i want to create sub domain. Can i handle this without enter in etc/host file.

Thanks in advance

**Comment by rusintez** [comment]
yes

**Comment by bmullan91** [comment]
@surendrakumar1992 Did you figure out a solution?

**Comment by LotharVM** [comment]
Hi all,

@surendrakumar1992's question is exact my situation. @rusintez's answer looks good, but is not including any 'does the user exists-check', right? As the subdomain should be available _after_ registration, it should not be accessible _before_ the username is registered. 

I'm using Passportjs for authentication in my app, where a user's username will be the subdomain. Any suggestion how to achieve my required 'subdomain only available if username exists' situation?

Really appreciated!

Regards,
Lothar

**Comment by rusintez** [comment]
@LotharVM, like in example above

```javascript

// render a page
app.get('/', function(req, res) {
  // no subdomain
  if (!req.subdomain) {
    // render landing page
    res.render('home');
  } else {
    // render subdomain specific data
    User.findOne({ subdomain: req.subdomain }, function(err, user) {
      if (!err && user) {
        return res.render('user-page', { subdomain: req.subdomain });
      } else {
        res.render('404');
      }
    });
  }
});

```

Hope this makes sense.

**Comment by LotharVM** [comment]
@rusintez, that makes perfect sense! Although I cannot make it work completely.. The first part is working fine; when I go to domain.com it shows the homepage and when I go to sub.domain.com it shows me the signup page. 

The problem is that it _always_ shows me the signup page, even when the subdomain matches a username in the database. I changed `{ subdomain: req.subdomain }` in your code to `{ username: req.subdomain }` as I'm using the `username` field in MongoDB to store the usernames. I'm not sure if that's the correct way, but when I copy/paste your code it isn't working either - it gives me the same result..


```javascript  
// render a page
app.get('/', function(req, res) {
  // no subdomain
  if (!req.subdomain) { 
  // render landing page
     res.render('home');
   } else {
   // render subdomain specific data
   User.findOne({ username: req.subdomain }, function(err, user) {
     if (!err && user) {
       res.render('contact');
     } else {
       // no user with this subdomain
       res.render('account/signup');
     }
   });
 }
});
```

**Comment by rusintez** [comment]
Do you have this code **preceding** your route?
``` javascript

// get your dynamic subdomain

app.use(function(req, res, next) {
  if (!req.subdomains.length || req.subdomains.slice(-1)[0] === 'www') return next();
  // otherwise we have subdomain here
  var subdomain = req.subdomains.slice(-1)[0];
  // keep it
  req.subdomain = subdomain;
  next();
});


```

**Comment by LotharVM** [comment]
@rusintez Yes!

**Comment by LotharVM** [comment]
I got it working! 
```javascript
User.findOne({ subdomain: req.subdomain }, function(err, user) {
```
should be
```javascript
User.findOne({ 'profile.subdomain': req.subdomain }, function(err, user) {
```
Because my username field is a subfield of 'profile'. Stupid mistake..

Thanks for the help @rusintez 👍

**Comment by ankit-bhawnani** [comment]
this "issue" can be closed now @bmullan91

**Comment by juliocanares** [comment]
I think @rusintez you mean a CNAME record, because you are pointing to a hostname not a ip

**Comment by biplabmalakar** [comment]
Gd mrng everyone.
I am new in angular and node.js. Now I am tring to make subdomain for each user and I am able to make by the above code. Now question is when user request for my page he/she need to enter my register domain, so question is how i can run my web application using user register subdomain.
Means if enter app.example.com---> application 1
biplab.example.com---> apllication1
And in my case i am not able to render web page from my server, because my server(node.js) and web page(angular2) are seperate. I can only verify the user by server.

**Comment by juliocanares** [comment]
@biplabmalakar is your web app an static one? or is it serve by a serve you control?

case 1 you can get the subdomain from the `window.location.href`, and then send a request to your server to get the user info.
case 2 get the subdomain with this library and send it to the your server too.

**Comment by biplabmalakar** [comment]
@juliocanares Data is serve by the server, for that  i make request. Means I don't need to alias my domain name by each user selected name. When I create domain in server It will run my angular application automatically and using subdomain name i can retrive user data from server.

**Comment by abdokouta** [comment]
@rusintez i'm interesting about the example u provide but in my situation i would like to integrate company account like companyname.myproject.com then after validating company name it will redirect the user to login my point is to create company account so that it have all company data and users and there is a lots of website doing that the most popular is slack any suggestions or ideas?

**Comment by rusintez** [comment]
@abdokouta, same as in above code.

**Comment by sameercodes** [comment]
In my etc/hosts file:

127.0.0.1       smallscale.com
127.0.0.1       hello.smallscale.com

I am using this library and its working good, if i hit smallscale.com i get one route, if i hit subdomain url its correctly going into another route.

My Question is i am putting this:

app.use(subdomain('hello', router));  // putting hello static in my express file

Any way to use dynamically? i mean dynamic number of sub-domains? with out putting static router file in my express code?

**Comment by rusintez** [comment]
yes, @sameercodes. just like above in #issuecomment-225441455

**Comment by sameercodes** [comment]
@rusintez yes its working! but if this works there is no use of this library? because the above code is working without this library! 😛

**Comment by rusintez** [comment]
how about https://github.com/bmullan91/express-subdomain#wildcards ?

**Comment by sameercodes** [comment]
I dont about that wilcards ! @rusintez 

But this one perfectly working 💯

Hi friends i got solution for dynamic domain to work locally:

Use nginx as a server!

If use using apache server, stop that and install nginx 

first add all your domains and subdomains in /etc/hosts: (without this you can't able to make work in local system)

127.0.0.1 github.com
127.0.0.1 sameer.github.com

edit your nginx.conf file: Set a nginx reverse proxy

Add your node js project port, in my project i am using 5000, so i put 5000

```
server {
        listen 80;
        server_name github.com; 
        location / {
            proxy_pass         http://localhost:5000; 
            proxy_http_version 1.1;
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    server {
            listen 80;
            server_name *.github.com;
            location / {
                proxy_pass         http://localhost:5000; 
                proxy_http_version 1.1;
                proxy_set_header Host      $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }

```
Instead of app.use(subdomain('yourstuff', router)); // static way
Place the below code:

```javascript
// get your dynamic subdomain
app.use(function(req, res, next) {
  if (!req.subdomains.length || req.subdomains.slice(-1)[0] === 'www') return next();
  // otherwise we have subdomain here
  var subdomain = req.subdomains.slice(-1)[0];
  // keep it
  req.subdomain = subdomain;
  next();
});


// render a page
app.get('/', function(req, res) {
  // no subdomain
  if (!req.subdomain) {
    // render landing page
    res.render('home');
  } else {
    // render subdomain specific data
    res.render('user-page');
  }
});
```
